### PR TITLE
Cleaned up AppDelegate, removed redundant viewControllers-setting code.

### PR DESCRIPTION
**Pull request by SuperWomble**
For your consideration! The first Pull Request!

This just cleans up the AppDelegate file.

It also removes the setting of the ExampleTableViewController's 'title' property.

That should be done in ExampleTableViewController's viewDidLoad() method, according to any Model data passed to the view controller.

### CODE REVIEW

**Comment by SuperWomble** [comment]
nudge nudge

**Comment by SuperWomble** [comment]
nudge nudge

**Comment by loosestar** [comment]
Trying to work out what's going on. My project doesn't seem to even have the file. Repulling...

**Comment by SuperWomble** [comment]
What's the progress on this? You should see a button like "Resolve Conflicts".

**Comment by loosestar** [comment]
I've attempted to resolve conflicts using the suggested button, but GH/s web interface hangs on "Resolving Conflicts". 
image

I'd suspected the problem was a corrupt pbxproj file, but considering it's part of the xcodeproj package, that seems unlikely, particularly as the project opens and compiles. Seeing if I have any luck with the web editor now.

**Comment by loosestar** [comment]
I appear to have cleaned up AppDelegate, though there are numerous conflicts in Breakpoints_v2.xcbkptlist, visibly stemming from values of timestamps and starting/ending column numbers.
A little nervous to manually alter these as a) I don't really know what I'm doing, and b) see a. Need to read up on such conflicts.

**Pull request closed without merging**
